name: CI

on:
  - push
  - pull_request

jobs:
  Tests:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install

      - name: Install depencencies
        run: uv sync --all-extras --dev

      - name: Lint
        run: uv run ruff check

      - name: Format
        run: uv run ruff format

      - name: Test
        run: uv run pytest --cov -v -s