name: CI

on:
  - push

jobs:
  Tests:
    name: Validate & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install depencencies
        run: uv sync --all-extras --dev

      - name: Lint
        run: uv run ruff check --output-format=github

      - name: Format
        run: uv run ruff format

      - name: Test
        env:
          SECRECY_TESTS_1PW_ITEM_ID: ${{ secrets.SECRECY_TESTS_1PW_ITEM_ID }}
          SECRECY_TESTS_1PW_VAULT_ID: ${{ secrets.SECRECY_TESTS_1PW_VAULT_ID }}
          SECRECY_TESTS_1PW_SERVICE_ACCOUNT_TOKEN: ${{ secrets.SECRECY_TESTS_1PW_SERVICE_ACCOUNT_TOKEN }}
          SECRECY_TESTS_AWS_ACCESS_KEY_ID: ${{ secrets.SECRECY_TESTS_AWS_ACCESS_KEY_ID }}
          SECRECY_TESTS_AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRECY_TESTS_AWS_SECRET_ACCESS_KEY }}
          SECRECY_TESTS_AWS_DEFAULT_REGION: ${{ secrets.SECRECY_TESTS_AWS_DEFAULT_REGION }}
          SECRECY_TESTS_AWS_SECRET_ID : ${{ secrets.SECRECY_TESTS_AWS_SECRET_ID  }}
        run: uv run pytest -vvv -rsx --cov --cov-report xml --junitxml=testreport.junit.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

